/**
 * onboard.test.ts — Unit tests for the onboarding guide builder.
 *
 * Tests: buildOnboardingGuide produces markdown sections covering
 * project overview, architecture layers, concepts, file map, hotspots.
 */

import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { GraphStore } from "../graph.js";
import type { KnowledgeGraph } from "../graph.js";
import { buildOnboardingGuide } from "../onboard.js";
import { writeFileSync, mkdirSync, rmSync } from "fs";
import { join } from "path";

// ─── Test Graph Fixture ────────────────────────────────────────────────────────

const TEST_GRAPH: KnowledgeGraph = {
  version: "1.0.0",
  kind: "codebase",
  project: {
    name: "onboard-test",
    languages: ["typescript"],
    frameworks: ["bun"],
    description: "Onboarding guide test graph",
    analyzedAt: "2025-01-01",
    gitCommitHash: "abc123",
  },
  nodes: [
    { id: "file:index.ts", type: "file", name: "index.ts", filePath: "src/index.ts", summary: "Server entry point", tags: ["server"], complexity: "simple" },
    { id: "file:graph.ts", type: "file", name: "graph.ts", filePath: "src/graph.ts", summary: "Graph store module", tags: ["graph"], complexity: "complex" },
    { id: "file:routes.ts", type: "file", name: "routes.ts", filePath: "src/routes.ts", summary: "API route handlers", tags: ["api"], complexity: "moderate" },
    { id: "fn:graph.ts:search", type: "function", name: "search", filePath: "src/graph.ts", summary: "Search the graph", tags: ["query"], complexity: "complex" },
    { id: "concept:mvc", type: "concept", name: "MVC Pattern", summary: "Model-View-Controller architecture", tags: ["architecture"], complexity: "simple" },
  ],
  edges: [
    { source: "file:graph.ts", target: "fn:graph.ts:search", type: "contains" },
    { source: "file:routes.ts", target: "file:graph.ts", type: "imports" },
  ],
  layers: [
    { id: "core", name: "Core", description: "Core data layer", nodeIds: ["file:graph.ts", "fn:graph.ts:search"] },
    { id: "api", name: "API", description: "HTTP API layer", nodeIds: ["file:routes.ts"] },
  ],
  tour: [
    { order: 1, title: "Get Started", description: "Start with the entry point", nodeIds: ["file:index.ts"] },
  ],
};

// ─── Setup ──────────────────────────────────────────────────────────────────────

const ROOT = import.meta.dir.replace(/[/\\]src[/\\]__tests__$/, "");
const tmpDir = join(ROOT, "__tmp_onboard_test__");
const graphPath = join(tmpDir, "test-graph.json");
let store: GraphStore;

beforeAll(() => {
  mkdirSync(tmpDir, { recursive: true });
  writeFileSync(graphPath, JSON.stringify(TEST_GRAPH, null, 2));
  store = new GraphStore(graphPath);
  store.load();
});

afterAll(() => {
  try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
});

// ─── Tests ──────────────────────────────────────────────────────────────────────

describe("buildOnboardingGuide", () => {
  let guide: string;

  beforeAll(() => {
    guide = buildOnboardingGuide(store);
  });

  test("produces markdown string", () => {
    expect(typeof guide).toBe("string");
    expect(guide.length).toBeGreaterThan(100);
  });

  test("includes project name as heading", () => {
    expect(guide).toContain("# onboard-test");
  });

  test("includes project description", () => {
    expect(guide).toContain("Onboarding guide test graph");
  });

  test("includes languages and frameworks", () => {
    expect(guide).toContain("typescript");
    expect(guide).toContain("bun");
  });

  test("includes Architecture section when layers exist", () => {
    expect(guide).toContain("## Architecture");
    expect(guide).toContain("Core");
    expect(guide).toContain("API");
  });

  test("includes Key Concepts section when concept nodes exist", () => {
    expect(guide).toContain("## Key Concepts");
    expect(guide).toContain("MVC Pattern");
    expect(guide).toContain("Model-View-Controller");
  });

  test("includes Getting Started section when tour exists", () => {
    expect(guide).toContain("## Getting Started");
    expect(guide).toContain("Get Started");
  });

  test("includes File Map section for file nodes with filePath", () => {
    expect(guide).toContain("## File Map");
    expect(guide).toContain("src/index.ts");
    expect(guide).toContain("src/graph.ts");
  });

  test("includes Complexity Hotspots for complex nodes", () => {
    expect(guide).toContain("## Complexity Hotspots");
    expect(guide).toContain("graph.ts");
  });

  test("includes component counts", () => {
    expect(guide).toContain("5 nodes");
    expect(guide).toContain("2 relationships");
  });

  test("includes footer with version", () => {
    expect(guide).toContain("Generated by learning-anything");
    expect(guide).toContain("1.0.0");
  });

  test("includes tour language lesson when present", () => {
    // Our test tour doesn't have a language lesson, so verify absence
    expect(guide).not.toContain("Language Tip");
  });
});

describe("buildOnboardingGuide — minimal graph", () => {
  test("handles graph with no layers gracefully", () => {
    const minimalGraph: KnowledgeGraph = {
      version: "1.0.0",
      kind: "codebase",
      project: {
        name: "minimal",
        languages: [],
        frameworks: [],
        description: "Minimal",
        analyzedAt: "2025-01-01",
        gitCommitHash: "abc",
      },
      nodes: [
        { id: "fn:a", type: "function", name: "a", summary: "fn a", tags: [], complexity: "simple" },
      ],
      edges: [],
      layers: [],
      tour: [],
    };

    const tmpMinimal = join(ROOT, "__tmp_onboard_minimal__");
    mkdirSync(tmpMinimal, { recursive: true });
    const minPath = join(tmpMinimal, "minimal.json");
    writeFileSync(minPath, JSON.stringify(minimalGraph, null, 2));
    const minStore = new GraphStore(minPath);
    minStore.load();
    const minGuide = buildOnboardingGuide(minStore);

    expect(minGuide).toContain("# minimal");
    expect(minGuide).not.toContain("## Architecture");
    expect(minGuide).not.toContain("## Key Concepts");
    expect(minGuide).not.toContain("## Getting Started");
    expect(minGuide).not.toContain("## File Map");

    try { rmSync(tmpMinimal, { recursive: true, force: true }); } catch {}
  });
});
